### ISSUE TITLE
General feedback up to practice 6

### ISSUE THREAD

**Issue by NC-MXTC** [jtracos/NCTaskManager#1]
The method needs to create a new instance of the requested list each time is called, this method functions similar to a singleton instead of a factory
https://github.com/jtracos/NCTaskManager/blob/99ceb5e04c4cdf924b8129b43c217c75dd49525e/src/main/java/mx/edu/j2se/trinidad/tasks/TaskListFactory.java#L10-L13

Currently the abstract class can be replaced with an interface, consider changes on the following methods because ArrayTaskList and LinkedTaskList have common functionality that can be semi-implemented in the abstract class
https://github.com/jtracos/NCTaskManager/blob/99ceb5e04c4cdf924b8129b43c217c75dd49525e/src/main/java/mx/edu/j2se/trinidad/tasks/AbstractTaskList.java#L34
https://github.com/jtracos/NCTaskManager/blob/99ceb5e04c4cdf924b8129b43c217c75dd49525e/src/main/java/mx/edu/j2se/trinidad/tasks/AbstractTaskList.java#L48
https://github.com/jtracos/NCTaskManager/blob/99ceb5e04c4cdf924b8129b43c217c75dd49525e/src/main/java/mx/edu/j2se/trinidad/tasks/AbstractTaskList.java#L55

Both methods are the same and can be implemented in the super class
https://github.com/jtracos/NCTaskManager/blob/99ceb5e04c4cdf924b8129b43c217c75dd49525e/src/main/java/mx/edu/j2se/trinidad/tasks/ArrayTaskList.java#L34-L36
https://github.com/jtracos/NCTaskManager/blob/99ceb5e04c4cdf924b8129b43c217c75dd49525e/src/main/java/mx/edu/j2se/trinidad/tasks/LinkedTaskList.java#L24-L26

Method toString needs to provide more information "at a glance", check the result of java lists like ArrayList<T> or Arrays.toString for examples of a desirable result
https://github.com/jtracos/NCTaskManager/blob/99ceb5e04c4cdf924b8129b43c217c75dd49525e/src/main/java/mx/edu/j2se/trinidad/tasks/AbstractTaskList.java#L78-L82

The implementation creates a shallow clone of the object and can create unexpected behaviors when modifying the clone object, original and clone objects should be independent from each other
https://github.com/jtracos/NCTaskManager/blob/99ceb5e04c4cdf924b8129b43c217c75dd49525e/src/main/java/mx/edu/j2se/trinidad/tasks/AbstractTaskList.java#L92-L99

Both methods are similar and can be moved to super class
https://github.com/jtracos/NCTaskManager/blob/99ceb5e04c4cdf924b8129b43c217c75dd49525e/src/main/java/mx/edu/j2se/trinidad/tasks/ArrayTaskList.java#L124-L128
https://github.com/jtracos/NCTaskManager/blob/99ceb5e04c4cdf924b8129b43c217c75dd49525e/src/main/java/mx/edu/j2se/trinidad/tasks/LinkedTaskList.java#L127-L130

From the details of the practice this method should prohibit extension by child classes
https://github.com/jtracos/NCTaskManager/blob/99ceb5e04c4cdf924b8129b43c217c75dd49525e/src/main/java/mx/edu/j2se/trinidad/tasks/AbstractTaskList.java#L64

**Comment by jtracos** [comment]
Changes have been commited
